name: "commit-master"

on:
  push:
    branches: 
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: deploy single function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: ${endpint}
        project_id: ${projectid}
        function_codetype: file
        function_urn: ${function_urn}
        function_file: ./python-sample/index.py

